/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sites
         * @description Read sites from `test_ui/sites.yml`.
         */
        get: operations["get_sites_api_sites_get"];
        put?: never;
        /**
         * Post Sites
         * @description Append a new site. The id is auto-generated server-side from the
         *     slugified name with a `-N` suffix on collision (so id-conflict 409s
         *     are structurally impossible — see `add_site`). Atomic write
         *     preserves operator-authored YAML comments.
         */
        post: operations["post_sites_api_sites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{site_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Site Route
         * @description Remove a site from sites.yml. On-disk per-site data dirs are NOT
         *     touched — historical artifacts remain readable; only future runs stop
         *     including this site.
         */
        delete: operations["delete_site_route_api_sites__site_id__delete"];
        options?: never;
        head?: never;
        /**
         * Patch Site
         * @description Mutate name and/or url. id is immutable — use DELETE + POST to rename.
         */
        patch: operations["patch_site_api_sites__site_id__patch"];
        trace?: never;
    };
    "/api/dates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dates */
        get: operations["get_dates_api_dates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Runs
         * @description List runs, newest first. `total` reflects the filtered set.
         */
        get: operations["get_runs_api_runs_get"];
        put?: never;
        /**
         * Post Runs
         * @description Spawn a new run as a subprocess. Returns 202 with the assigned ids.
         */
        post: operations["post_runs_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{db_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run By Id */
        get: operations["get_run_by_id_api_runs__db_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Sync */
        post: operations["post_sync_api_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{db_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Run Retry
         * @description Re-spawn a run with the same args as `db_id`.
         *
         *     Reads `args_json` off the original row + reconstructs the matching
         *     `RunRequest` subclass; from there it's the same path as `POST /api/runs`,
         *     so 409 / 412 still apply (a retry of an already-running comparison
         *     correctly conflicts).
         */
        post: operations["post_run_retry_api_runs__db_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{db_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Logs
         * @description Stream the subprocess log file. Always capped at 1 MB even without
         *     `tail` to prevent runaway responses.
         *
         *     Returns 404 if the row doesn't exist OR if the log file hasn't been
         *     created yet (the spawn opens it lazily — a row in `pending` for less
         *     than a few ms may have no log).
         */
        get: operations["get_run_logs_api_runs__db_id__logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{date}/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report Summary
         * @description Top-level metadata: manifest fields + per-result-type counts.
         */
        get: operations["get_report_summary_api_reports__date___run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{date}/{run_id}/urls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report Urls
         * @description List of URLs in the report with their result_type + severity.
         */
        get: operations["get_report_urls_api_reports__date___run_id__urls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{date}/{run_id}/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report Url Detail
         * @description Per-URL detail: AI analysis verbatim + structured_data + screenshot
         *     inventory (the actual bytes come from the SCREENSHOT route).
         */
        get: operations["get_report_url_detail_api_reports__date___run_id__url_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{date}/{run_id}/screenshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report Screenshot
         * @description Return one PNG (baseline / current / diff) for one URL.
         *
         *     Query-param typing on `which` is FastAPI-enforced (a different value
         *     yields 422). `url_id` is validated against the actual on-disk
         *     children, so a bogus value can't traverse OR enumerate.
         */
        get: operations["get_report_screenshot_api_reports__date___run_id__screenshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Liveness check. Never raises — degraded states surface as `False`s.
         *
         *     Does NOT use `DbDep`: if the DB itself can't be opened (disk full,
         *     permission denied on the WAL file), the dependency would raise BEFORE
         *     the handler runs and FastAPI would 500. We want the failure to
         *     surface as `db_ok=False` instead — that's the entire point of having
         *     a health route.
         *
         *     The AI analyzer probe is bounded to 2s so a hung analyzer container
         *     can't make `/api/health` itself appear hung. The overall `ok` mirrors
         *     `db_ok` only — the analyzer being down doesn't invalidate the dashboard
         *     (it just disables AI-dependent UI affordances client-side).
         */
        get: operations["get_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BaselineRunRequest */
        BaselineRunRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "baseline";
        };
        /** ComparatorRunRequest */
        ComparatorRunRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "comparator";
            /** Baseline Run Id */
            baseline_run_id?: string | null;
            /** Current Run Id */
            current_run_id?: string | null;
        };
        /** CurrentRunRequest */
        CurrentRunRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "current";
        };
        /**
         * DatesOut
         * @description Per-kind list of date directories present on disk.
         *
         *     The frontend uses this to populate date pickers without scanning
         *     the filesystem itself. Dates are DD-MM-YYYY strings, sorted descending
         *     (newest first) so the UI can default to the most recent.
         */
        DatesOut: {
            /** Baseline */
            baseline?: string[];
            /** Current */
            current?: string[];
            /** Comparator */
            comparator?: string[];
            /** Report */
            report?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthOut
         * @description Quick liveness probe for the dashboard.
         *
         *     `db_ok` False → SQLite open or migration failed; the dashboard is
         *     running in a degraded state and most routes will 500.
         *     `ai_analyzer_ok` is checked with a 2s timeout — the dashboard never
         *     hangs on a slow analyzer; a False here just disables AI-dependent
         *     UI affordances client-side.
         */
        HealthOut: {
            /** Ok */
            ok: boolean;
            /** Db Ok */
            db_ok: boolean;
            /** Ai Analyzer Ok */
            ai_analyzer_ok: boolean;
        };
        /** ReportRunRequest */
        ReportRunRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "report";
            /** Date */
            date?: string | null;
        };
        /**
         * ReportSummaryOut
         * @description `GET /api/reports/{date}/{run_id}` — top-level summary. `run_id`,
         *     `started_at`, `finished_at`, `url_count` come from the manifest;
         *     `severity_counts` is computed from the per-URL files.
         */
        ReportSummaryOut: {
            /** Date */
            date: string;
            /** Run Id */
            run_id: string;
            /** Started At */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Url Count */
            url_count: number;
            /** Severity Counts */
            severity_counts?: {
                [key: string]: number;
            };
        };
        /**
         * ReportUrlDetail
         * @description `GET /api/reports/{date}/{run_id}/url?id=<url_id>` — the per-URL
         *     AI analysis JSON, returned verbatim from disk.
         *
         *     Typed as `dict` because the AI analysis schema lives in
         *     `test_ui/contracts/` and varies by `result_type` — wiring up a full
         *     discriminated union here would duplicate ~200 LOC of pydantic models
         *     that already exist in the contracts package, with the only payoff
         *     being typed access in the React drill-in (which renders it as JSON
         *     anyway). Acceptable type-loss for the MVP; tighten if the UI needs
         *     typed access.
         */
        ReportUrlDetail: {
            /** Url Id */
            url_id: string;
            /**
             * Result Type
             * @enum {string}
             */
            result_type: "analysis_success" | "analysis_error" | "no_changes" | "ai_disabled" | "unknown";
            /** Analysis */
            analysis: {
                [key: string]: unknown;
            };
            /** Structured Data */
            structured_data?: {
                [key: string]: unknown;
            } | null;
            /** Screenshots */
            screenshots?: ("baseline" | "current" | "visual_diff")[];
        };
        /**
         * ReportUrlSummary
         * @description One row in the `/api/reports/{date}/{run_id}/urls` listing.
         *
         *     `severity` is only populated for `result_type='analysis_success'` —
         *     the other result types don't have a meaningful severity. The frontend
         *     can surface a colored pill keyed off either `result_type` (always
         *     present) or `severity` (success-only).
         */
        ReportUrlSummary: {
            /** Url Id */
            url_id: string;
            /**
             * Result Type
             * @enum {string}
             */
            result_type: "analysis_success" | "analysis_error" | "no_changes" | "ai_disabled" | "unknown";
            /** Severity */
            severity?: string | null;
            /** Url */
            url?: string | null;
        };
        /** ReportUrlsOut */
        ReportUrlsOut: {
            /** Items */
            items: components["schemas"]["ReportUrlSummary"][];
        };
        /**
         * RunListOut
         * @description Paginated list response.
         */
        RunListOut: {
            /** Items */
            items: components["schemas"]["RunRow"][];
            /** Total */
            total: number;
        };
        /**
         * RunRow
         * @description One row from `runs`, projected for the wire.
         *
         *     `args_json` and `command_json` are exposed as parsed objects (not raw
         *     strings) — saves the frontend a JSON.parse and gives openapi-typescript
         *     a typed shape to work with.
         */
        RunRow: {
            /** Id */
            id: number;
            /** Run Id */
            run_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "baseline" | "current" | "comparator" | "report";
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "done" | "failed" | "interrupted";
            /** Created At */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Date Dir */
            date_dir?: string | null;
            /** Args */
            args?: {
                [key: string]: unknown;
            };
            /** Command */
            command?: string[];
            /** Exit Code */
            exit_code?: number | null;
            /** Error */
            error?: string | null;
            /** Pid */
            pid?: number | null;
            /** Pgid */
            pgid?: number | null;
            /** Pid Start Time */
            pid_start_time?: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "dashboard" | "discovered" | "cli";
        };
        /**
         * RunSpawnedOut
         * @description 202 response from `POST /api/runs`. `db_id` lets the frontend poll
         *     `/api/runs/{db_id}` for status; `run_id` lets it correlate against the
         *     on-disk run dir as soon as the subprocess produces it.
         */
        RunSpawnedOut: {
            /** Db Id */
            db_id: number;
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "done" | "failed" | "interrupted";
        };
        /**
         * SiteCreateIn
         * @description `POST /api/sites` body. `id` is auto-generated server-side from the
         *     slugified name + numeric dedup suffix; the client never sets it.
         *
         *     `max_length` caps mirror the underlying `Site` model — defending at
         *     the wire boundary too means a 100KB URL gets rejected with a clear
         *     422 instead of bloating sites.yml at the persistence layer.
         */
        SiteCreateIn: {
            /** Name */
            name: string;
            /** Url */
            url: string;
        };
        /**
         * SiteOut
         * @description A site as returned by `GET /api/sites`.
         */
        SiteOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Url */
            url: string;
        };
        /**
         * SiteUpdateIn
         * @description `PATCH /api/sites/{id}` body. Both fields optional — operator can
         *     rename without changing the URL or vice versa. `id` is immutable
         *     (changing it would invalidate existing per-site data dirs); the URL
         *     path component is authoritative.
         */
        SiteUpdateIn: {
            /** Name */
            name?: string | null;
            /** Url */
            url?: string | null;
        };
        /**
         * SyncOut
         * @description `POST /api/sync` result. `synced` is the count of NEW rows inserted.
         *
         *     Re-running sync should be a no-op (returning `synced=0`) once the DB
         *     has caught up to the on-disk state — the test pins this idempotency.
         */
        SyncOut: {
            /** Synced */
            synced: number;
            /** Scanned */
            scanned: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_sites_api_sites_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteOut"][];
                };
            };
        };
    };
    post_sites_api_sites_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteOut"];
                };
            };
            /** @description Body validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_site_route_api_sites__site_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No site with this id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_site_api_sites__site_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteOut"];
                };
            };
            /** @description No site with this id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Body validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_dates_api_dates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatesOut"];
                };
            };
        };
    };
    get_runs_api_runs_get: {
        parameters: {
            query?: {
                /** @description Filter by kind */
                kind?: string | null;
                /** @description Filter by status */
                status?: string | null;
                /** @description Filter to runs whose date_dir matches (DD-MM-YYYY). Lets the Reports page list runs for a single date without client-side truncation. */
                date_dir?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_runs_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BaselineRunRequest"] | components["schemas"]["CurrentRunRequest"] | components["schemas"]["ComparatorRunRequest"] | components["schemas"]["ReportRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSpawnedOut"];
                };
            };
            /** @description Conflicting in-flight run for the same kind+date */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Workflow precondition not met (upstream not complete) */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_by_id_api_runs__db_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                db_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_sync_api_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncOut"];
                };
            };
        };
    };
    post_run_retry_api_runs__db_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                db_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSpawnedOut"];
                };
            };
            /** @description No such db_id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflicting in-flight run */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Workflow precondition not met */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_logs_api_runs__db_id__logs_get: {
        parameters: {
            query?: {
                /** @description Return only the last N bytes of the log (max 1048576). */
                tail?: number | null;
            };
            header?: never;
            path: {
                db_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/plain": unknown;
                };
            };
            /** @description No row, or no log file yet */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_summary_api_reports__date___run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportSummaryOut"];
                };
            };
            /** @description Malformed date or run_id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No report for this date+run_id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_urls_api_reports__date___run_id__urls_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportUrlsOut"];
                };
            };
            /** @description Malformed date or run_id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No report for this date+run_id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_url_detail_api_reports__date___run_id__url_get: {
        parameters: {
            query: {
                /** @description The url_id (per-site directory name) */
                id: string;
            };
            header?: never;
            path: {
                date: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportUrlDetail"];
                };
            };
            /** @description Malformed date / run_id / url_id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such url_id in this report */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_screenshot_api_reports__date___run_id__screenshot_get: {
        parameters: {
            query: {
                url_id: string;
                which: "baseline" | "current" | "diff";
            };
            header?: never;
            path: {
                date: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "image/png": unknown;
                };
            };
            /** @description Malformed parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such url_id, or no screenshot of that kind */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
}
